"""Execution enums shared across live paper, historical replay, and calibration."""

from __future__ import annotations

from enum import Enum


class InternalOrderState(str, Enum):
    LOCAL_CREATED = "LOCAL_CREATED"
    RISK_ACCEPTED = "RISK_ACCEPTED"
    SUBMIT_QUEUED = "SUBMIT_QUEUED"
    SUBMIT_INFLIGHT = "SUBMIT_INFLIGHT"
    VENUE_ACCEPTED = "VENUE_ACCEPTED"
    WORKING = "WORKING"
    PARTIALLY_MATCHED_PROVISIONAL = "PARTIALLY_MATCHED_PROVISIONAL"
    MATCHED_PROVISIONAL = "MATCHED_PROVISIONAL"
    CANCEL_REQUESTED = "CANCEL_REQUESTED"
    CANCEL_INFLIGHT = "CANCEL_INFLIGHT"
    REPLACE_REQUESTED = "REPLACE_REQUESTED"
    EXPIRED_PENDING = "EXPIRED_PENDING"
    SETTLEMENT_PENDING = "SETTLEMENT_PENDING"
    CONFIRMED = "CONFIRMED"
    FAILED_REVERSED = "FAILED_REVERSED"
    CANCELED = "CANCELED"
    REJECTED = "REJECTED"


class FinalityState(str, Enum):
    TRADE_ID_ASSIGNED = "TRADE_ID_ASSIGNED"
    MATCHED_NOT_BROADCASTED = "MATCHED_NOT_BROADCASTED"
    MATCHED = "MATCHED"
    MINED = "MINED"
    CONFIRMED = "CONFIRMED"
    RETRYING = "RETRYING"
    FAILED = "FAILED"


class CapacityStatus(str, Enum):
    IN_DOMAIN_CALIBRATED = "IN_DOMAIN_CALIBRATED"
    CAPACITY_STRESSED = "CAPACITY_STRESSED"
    REJECT_UNCALIBRATED_CAPACITY = "REJECT_UNCALIBRATED_CAPACITY"


class ImpactMode(str, Enum):
    NO_IMPACT_REPLAY = "NO_IMPACT_REPLAY"
    CAPACITY_GATED_REPLAY = "CAPACITY_GATED_REPLAY"
    STRESS_IMPACT = "STRESS_IMPACT"


class PnlTier(str, Enum):
    RAW_SHADOW = "RAW_SHADOW"
    TAKER_CALIBRATED_IN_DOMAIN = "TAKER_CALIBRATED_IN_DOMAIN"
    TAKER_CONSERVATIVE = "TAKER_CONSERVATIVE"
    TAKER_EXTRAPOLATED = "TAKER_EXTRAPOLATED"
    MAKER_UNCALIBRATED = "MAKER_UNCALIBRATED"
    MAKER_CALIBRATED_IN_DOMAIN = "MAKER_CALIBRATED_IN_DOMAIN"
    REAL_MATCHED_PROVISIONAL = "REAL_MATCHED_PROVISIONAL"
    REAL_CONFIRMED = "REAL_CONFIRMED"
