"""Market registry enum values used by the paper registry service."""

from __future__ import annotations

from enum import Enum


class StrEnum(str, Enum):
    """Python 3.10-compatible subset of enum.StrEnum."""


class MarketState(StrEnum):
    DISCOVERED = "DISCOVERED"
    DISCOVERED_PENDING_BOOK = "DISCOVERED_PENDING_BOOK"
    TRADABLE_PENDING_BOOK = "TRADABLE_PENDING_BOOK"
    LIVE = "LIVE"
    STALE = "STALE"
    CLOSING = "CLOSING"
    RESOLVED = "RESOLVED"
    ARCHIVED = "ARCHIVED"
    NO_CLOB_BOOK = "NO_CLOB_BOOK"
    BOOK_PROBE_ERROR = "BOOK_PROBE_ERROR"
    INVALID_METADATA = "INVALID_METADATA"


class BookQuality(StrEnum):
    READY_HIGH = "READY_HIGH"
    READY_MEDIUM = "READY_MEDIUM"
    STALE = "STALE"
    GAP = "GAP"
    NO_SNAPSHOT = "NO_SNAPSHOT"
    DISCONNECTED = "DISCONNECTED"
    NO_CLOB_BOOK = "NO_CLOB_BOOK"
    PROBE_ERROR = "PROBE_ERROR"
    EMPTY = "EMPTY"
    ONE_SIDED = "ONE_SIDED"
    NOT_CHECKED = "NOT_CHECKED"


class MarketLifecycleEventType(StrEnum):
    MARKET_DISCOVERED = "MARKET_DISCOVERED"
    MARKET_METADATA_UPDATED = "MARKET_METADATA_UPDATED"
    TOKEN_ADDED = "TOKEN_ADDED"
    TOKEN_REMOVED = "TOKEN_REMOVED"
    BOOK_PROBE_REQUESTED = "BOOK_PROBE_REQUESTED"
    BOOK_READY = "BOOK_READY"
    BOOK_STALE = "BOOK_STALE"
    BOOK_GAP = "BOOK_GAP"
    TRADING_HALTED = "TRADING_HALTED"
    MARKET_CLOSED = "MARKET_CLOSED"
    MARKET_RESOLVED = "MARKET_RESOLVED"
    MARKET_ARCHIVED = "MARKET_ARCHIVED"
    ASSET_SUBSCRIBE_REQUESTED = "ASSET_SUBSCRIBE_REQUESTED"
    ASSET_UNSUBSCRIBE_REQUESTED = "ASSET_UNSUBSCRIBE_REQUESTED"
    ASSET_EXECUTION_ENABLED = "ASSET_EXECUTION_ENABLED"
    ASSET_EXECUTION_DISABLED = "ASSET_EXECUTION_DISABLED"
